// ═══════════════════════════════════════════════════════════════════════
// dev-03 LightGBM Runtime — v4 cross-season-validated engine
//
// Browser-side inference for the dev-03 Bayesian Ensemble (5 bagged LightGBM
// Tweedie models per home/away). Plus m6_benter log-pool blender for fusing
// model probs with the (vig-removed) market probs.
//
// Differences from `lgbm-runtime.ts` (v2):
//   - 5-model bagging: predict each model, return mean + variance over the
//     5-prediction distribution (the variance feeds m7_kelly's
//     variance-shrinkage formula).
//   - Categorical features: `league` is the 17th feature; the tree dump uses
//     decision_type "==" with `||`-separated category INDICES. The TS
//     runtime maps a league string to its categorical index via
//     `pandas_categorical[0]` (alphabetical canonical ordering, baked at
//     train-time).
//   - 16 numeric features + 1 categorical. Order is LOCKED — see
//     `FEATURE_NAMES_LOCKED` constant. Feature-builder callers MUST emit
//     values in this exact order.
//
// Source artifact: `public/dev03-model.json` (~7.5 MB), generated by
//   `tools/v4/export_dev03_to_json.py` from the in-repo Python pickles.
// Re-export after each retrain.
//
// Status (2026-05-21): runtime + golden tests shipped. Feature-builder TS
// port (m2_lambda + EloCalculator + TeamMomentumCalculator) is the follow-up
// sprint and not part of this file. Until then, this runtime is a building
// block — Goldilocks UI still displays the "🎯 Dev-03" recommendation badge
// based on `bet-edge-policy.ts`, but auto-routing must wait for features.
// ═══════════════════════════════════════════════════════════════════════

// ─── Types ───────────────────────────────────────────────────────────

interface TreeNode {
  // Internal node fields
  split_feature?: number;
  threshold?: number | string; // number for "<=", string "1||5||8" for "=="
  decision_type?: "<=" | "==";
  default_left?: boolean;
  missing_type?: string;
  left_child?: TreeNode;
  right_child?: TreeNode;
  // Leaf field
  leaf_value?: number;
}

interface Dev03Model {
  seed: number;
  n_trees: number;
  trees: TreeNode[];
}

interface Dev03Ensemble {
  n_models: number;
  seeds: number[];
  models: Dev03Model[];
}

interface BenterLigaWeights {
  beta_model: number;
  beta_market: number;
  n_samples: number;
  fit_success: boolean;
  source: string;
}

interface BenterWeights {
  default_betas: [number, number];
  global_weights: [number, number] | null;
  liga_weights: Record<string, BenterLigaWeights>;
  min_liga_samples: number;
}

interface GoldenFeatures {
  home_attack_ratio: number;
  home_defense_ratio: number;
  away_attack_ratio: number;
  away_defense_ratio: number;
  home_ess: number;
  away_ess: number;
  league_home_avg: number;
  league_away_avg: number;
  league_home_advantage: number;
  lambda_h_naive: number;
  lambda_a_naive: number;
  attack_defense_ratio_h: number;
  attack_defense_ratio_a: number;
  elo_diff: number;
  lineup_quality_diff: number;
  form_streak_diff: number;
  league: string;
}

export interface Dev03GoldenTest {
  name: string;
  features: GoldenFeatures;
  expected_home_lambda_mean: number;
  expected_home_lambda_var: number;
  expected_away_lambda_mean: number;
  expected_away_lambda_var: number;
}

export interface Dev03Model_FullPayload {
  version: string;
  engine: string;
  exported_at: string;
  rho: number;
  feature_names: string[];
  categorical_features: string[];
  pandas_categorical: string[][];
  home_ensemble: Dev03Ensemble;
  away_ensemble: Dev03Ensemble;
  benter: BenterWeights;
  golden_tests: Dev03GoldenTest[];
  meta: Record<string, unknown>;
}

/** Public — what the TS feature-builder will emit (numeric features in order). */
export interface Dev03FeatureInput {
  home_attack_ratio: number;
  home_defense_ratio: number;
  away_attack_ratio: number;
  away_defense_ratio: number;
  home_ess: number;
  away_ess: number;
  league_home_avg: number;
  league_away_avg: number;
  league_home_advantage: number;
  lambda_h_naive: number;
  lambda_a_naive: number;
  attack_defense_ratio_h: number;
  attack_defense_ratio_a: number;
  elo_diff: number;
  lineup_quality_diff: number;
  form_streak_diff: number;
  league: string; // resolved to categorical index internally
}

export interface Dev03Prediction {
  lambdaH_mean: number;
  lambdaH_var: number;
  lambdaA_mean: number;
  lambdaA_var: number;
  /** Per-model raw lambdas (5 home + 5 away) — exposed for diagnostics. */
  lambdaH_per_model: number[];
  lambdaA_per_model: number[];
}

// ─── Constants ──────────────────────────────────────────────────────

/**
 * Locked feature order. The trained model expects exactly these 17 features
 * in this exact order, with `league` (categorical) as the last column.
 *
 * Adding/removing/reordering features requires a new model tag (e.g. dev-04).
 */
export const FEATURE_NAMES_LOCKED: readonly string[] = [
  "home_attack_ratio",
  "home_defense_ratio",
  "away_attack_ratio",
  "away_defense_ratio",
  "home_ess",
  "away_ess",
  "league_home_avg",
  "league_away_avg",
  "league_home_advantage",
  "lambda_h_naive",
  "lambda_a_naive",
  "attack_defense_ratio_h",
  "attack_defense_ratio_a",
  "elo_diff",
  "lineup_quality_diff",
  "form_streak_diff",
  "league",
] as const;

/** Tweedie λ-clamp range (matches m2_lambda's LAMBDA_MIN / LAMBDA_MAX). */
const LAMBDA_MIN = 0.3;
const LAMBDA_MAX = 4.5;

// ─── Module State ───────────────────────────────────────────────────

let model: Dev03Model_FullPayload | null = null;
/**
 * Pre-computed (league → categorical index) lookup. Derived from
 * `pandas_categorical[0]` at load-time. Unknown leagues → -1 (LightGBM's
 * sentinel for missing categorical).
 */
let leagueIndex: Map<string, number> = new Map();

// ─── Tree Traversal ─────────────────────────────────────────────────

/**
 * For categorical-equality splits, the `threshold` is a `||`-separated string
 * of category INDICES that route LEFT. Parse to a Set<number> for O(1) lookup.
 * We cache the parsed set on the node itself to amortize cost across
 * predictions (mutating the loaded JSON in-place is safe — single owner).
 */
interface CategoricalNode extends TreeNode {
  _catSet?: Set<number>;
}

function getCategoricalSet(node: CategoricalNode): Set<number> {
  if (node._catSet) return node._catSet;
  const raw = String(node.threshold ?? "");
  const set = new Set<number>();
  for (const tok of raw.split("||")) {
    const n = Number(tok);
    if (Number.isFinite(n)) set.add(n);
  }
  node._catSet = set;
  return set;
}

function traverseTree(node: TreeNode, features: number[]): number {
  // Leaf
  if (node.leaf_value !== undefined) return node.leaf_value;

  const featIdx = node.split_feature!;
  const val = features[featIdx];
  const dt = node.decision_type;

  // Decide which child to descend
  let goLeft: boolean;
  if (dt === "<=") {
    // Standard numeric inequality. NaN handling matches LightGBM:
    //   - missing val + default_left=true → left
    //   - missing val + default_left=false → right
    if (Number.isNaN(val)) {
      goLeft = !!node.default_left;
    } else {
      goLeft = val <= (node.threshold as number);
    }
  } else if (dt === "==") {
    // Categorical equality. threshold is "1||5||8|…" — go LEFT if val is in the set.
    // Missing categorical (val === -1 or NaN) → default_left
    if (val < 0 || Number.isNaN(val)) {
      goLeft = !!node.default_left;
    } else {
      const set = getCategoricalSet(node as CategoricalNode);
      goLeft = set.has(val);
    }
  } else {
    // Unknown decision_type — default to right (safest, no false confidence)
    console.error(`[dev03-runtime] Unknown decision_type: ${dt}`);
    goLeft = false;
  }

  return traverseTree(goLeft ? node.left_child! : node.right_child!, features);
}

function predictOneModel(m: Dev03Model, features: number[]): number {
  // Sum all leaf values; trees include init_score baked into root tree's leaves.
  // Tweedie uses log-link, so final λ = exp(sum_of_leaves).
  let score = 0;
  for (const t of m.trees) {
    score += traverseTree(t, features);
  }
  return Math.exp(score);
}

// ─── Public API: Load ───────────────────────────────────────────────

/**
 * Load the dev-03 model JSON (typically fetched from `/dev03-model.json`).
 * Returns true on success, false on validation failure.
 *
 * Validates:
 *   - Both ensembles present + non-empty
 *   - n_models matches actual length
 *   - feature_names matches FEATURE_NAMES_LOCKED
 *   - pandas_categorical present + length matches one entry per categorical column
 */
export function loadDev03Model(json: Dev03Model_FullPayload): boolean {
  if (!json.home_ensemble?.models?.length || !json.away_ensemble?.models?.length) {
    console.error("[dev03-runtime] Invalid model: missing ensembles");
    return false;
  }
  if (json.home_ensemble.n_models !== json.home_ensemble.models.length) {
    console.error(
      `[dev03-runtime] home n_models mismatch: declared=${json.home_ensemble.n_models}, actual=${json.home_ensemble.models.length}`
    );
    return false;
  }
  if (json.away_ensemble.n_models !== json.away_ensemble.models.length) {
    console.error(
      `[dev03-runtime] away n_models mismatch: declared=${json.away_ensemble.n_models}, actual=${json.away_ensemble.models.length}`
    );
    return false;
  }
  if (json.feature_names.length !== FEATURE_NAMES_LOCKED.length) {
    console.error(
      `[dev03-runtime] feature dimension mismatch: model=${json.feature_names.length} vs locked=${FEATURE_NAMES_LOCKED.length}`
    );
    return false;
  }
  for (let i = 0; i < json.feature_names.length; i++) {
    if (json.feature_names[i] !== FEATURE_NAMES_LOCKED[i]) {
      console.error(
        `[dev03-runtime] feature[${i}] mismatch: model="${json.feature_names[i]}", locked="${FEATURE_NAMES_LOCKED[i]}"`
      );
      return false;
    }
  }
  if (!json.pandas_categorical?.length || !json.pandas_categorical[0]?.length) {
    console.error("[dev03-runtime] missing pandas_categorical[0] (league index map)");
    return false;
  }

  model = json;

  // Build league → category-index map. LightGBM uses alphabetical order
  // of the pandas Categorical, so the first entry is index 0.
  leagueIndex = new Map();
  json.pandas_categorical[0].forEach((leagueName, idx) => {
    leagueIndex.set(leagueName.toLowerCase().trim(), idx);
  });

  const nHomeTrees = json.home_ensemble.models.reduce((s, m) => s + m.n_trees, 0);
  const nAwayTrees = json.away_ensemble.models.reduce((s, m) => s + m.n_trees, 0);
  console.log(
    `[dev03-runtime] Loaded dev-03 model: ${json.home_ensemble.n_models}×${nHomeTrees / json.home_ensemble.n_models}H + ${json.away_ensemble.n_models}×${nAwayTrees / json.away_ensemble.n_models}A trees, ` +
    `${json.feature_names.length} features, ${leagueIndex.size} leagues, rho=${json.rho}`
  );
  return true;
}

/** Module-level guard — UI / engine routing should branch on this. */
export function isDev03ModelLoaded(): boolean {
  return model !== null;
}

/** Dixon-Coles ρ baked at training time (typically -0.094 for dev-03). */
export function getDev03Rho(): number {
  return model?.rho ?? -0.094;
}

/** Diagnostics — full feature_names exactly as the trained model expects. */
export function getDev03FeatureNames(): readonly string[] {
  return model?.feature_names ?? FEATURE_NAMES_LOCKED;
}

/** Lowercased + trimmed league → categorical-index, or -1 if unknown. */
export function leagueToCategoryIndex(league: string): number {
  if (!model) return -1;
  const norm = (league ?? "").toLowerCase().trim();
  const idx = leagueIndex.get(norm);
  return idx ?? -1;
}

// ─── Public API: Predict ────────────────────────────────────────────

/**
 * Convert a Dev03FeatureInput dict to the float-array shape that the trees
 * expect. The `league` string is mapped to its categorical index here.
 *
 * Returns null if any non-categorical feature is non-finite — guarding
 * against silent garbage from the feature builder.
 */
export function buildFeatureArray(input: Dev03FeatureInput): number[] | null {
  const arr: number[] = new Array(FEATURE_NAMES_LOCKED.length);
  for (let i = 0; i < FEATURE_NAMES_LOCKED.length; i++) {
    const name = FEATURE_NAMES_LOCKED[i] as keyof Dev03FeatureInput;
    if (name === "league") {
      arr[i] = leagueToCategoryIndex(input.league);
      // -1 is a valid category sentinel (missing). LightGBM's default-handling
      // routes via `default_left`. No null-return needed here.
      continue;
    }
    const v = input[name] as number;
    if (typeof v !== "number" || !Number.isFinite(v)) {
      console.error(
        `[dev03-runtime] non-finite feature "${name}" = ${v} — refusing to predict`
      );
      return null;
    }
    arr[i] = v;
  }
  return arr;
}

/**
 * Run the full Bayesian-ensemble forward pass. Returns mean + variance for
 * both home + away λ (variance feeds m7_kelly's shrinkage formula).
 *
 * Returns null if model not loaded, or if features are unprocessable.
 *
 * All output lambdas are clamped to [LAMBDA_MIN, LAMBDA_MAX].
 */
export function dev03Predict(input: Dev03FeatureInput): Dev03Prediction | null {
  if (!model) {
    console.error("[dev03-runtime] model not loaded");
    return null;
  }
  const features = buildFeatureArray(input);
  if (!features) return null;

  // Predict on each of the 5 bagged models and aggregate
  const homePreds = model.home_ensemble.models.map(m => predictOneModel(m, features));
  const awayPreds = model.away_ensemble.models.map(m => predictOneModel(m, features));

  const meanH = homePreds.reduce((s, x) => s + x, 0) / homePreds.length;
  const meanA = awayPreds.reduce((s, x) => s + x, 0) / awayPreds.length;
  // ddof=0 to match Python's `var(ddof=0)` — population variance for the
  // ensemble (we have ALL members, not a sample).
  const varH = homePreds.reduce((s, x) => s + (x - meanH) ** 2, 0) / homePreds.length;
  const varA = awayPreds.reduce((s, x) => s + (x - meanA) ** 2, 0) / awayPreds.length;

  // Clamp final lambdas (m2_lambda invariant)
  const lambdaH_mean = Math.max(LAMBDA_MIN, Math.min(LAMBDA_MAX, meanH));
  const lambdaA_mean = Math.max(LAMBDA_MIN, Math.min(LAMBDA_MAX, meanA));

  return {
    lambdaH_mean,
    lambdaH_var: varH,
    lambdaA_mean,
    lambdaA_var: varA,
    lambdaH_per_model: homePreds,
    lambdaA_per_model: awayPreds,
  };
}

// ─── Public API: Benter Blend ───────────────────────────────────────

/**
 * Log-pool softmax blend of model probs with market probs, using per-league
 * Benter weights. Returns blended probs (rows sum to 1).
 *
 * If model not loaded, or benter weights missing for league, falls back to:
 *   1. global_weights (β_model=0.71, β_market=0.30 for dev-03)
 *   2. default_betas (0.5, 0.5)
 *
 * Mirrors the Python `BenterBlender.blend` implementation byte-for-byte
 * (within float64 precision).
 *
 * @param pModel  model probs [H, D, A] — must sum to ~1
 * @param pMarket vig-removed market probs [H, D, A] — must sum to ~1
 * @param league  league code (case-insensitive)
 */
export function dev03BenterBlend(
  pModel: [number, number, number],
  pMarket: [number, number, number],
  league: string,
): [number, number, number] | null {
  if (!model) return null;

  const norm = (league ?? "").toLowerCase().trim();
  const liga = model.benter.liga_weights[norm];

  let beta_model: number;
  let beta_market: number;
  if (liga) {
    beta_model = liga.beta_model;
    beta_market = liga.beta_market;
  } else if (model.benter.global_weights) {
    [beta_model, beta_market] = model.benter.global_weights;
  } else {
    [beta_model, beta_market] = model.benter.default_betas;
  }

  // Clip + log
  const EPS = 1e-12;
  const logPm = pModel.map(p => Math.log(Math.max(EPS, Math.min(1, p))));
  const logPmk = pMarket.map(p => Math.log(Math.max(EPS, Math.min(1, p))));

  // Combined logits
  const logits = logPm.map((lm, i) => beta_model * lm + beta_market * logPmk[i]);

  // Softmax with numerical stability
  const maxLogit = Math.max(...logits);
  const exps = logits.map(x => Math.exp(x - maxLogit));
  const sum = exps.reduce((s, x) => s + x, 0);
  return [exps[0] / sum, exps[1] / sum, exps[2] / sum];
}

/**
 * Returns the per-Liga benter weights (or null if league not fitted).
 * Exposed for telemetry — e.g. "this league uses global-fallback" indicators.
 */
export function getDev03BenterWeights(league: string): BenterLigaWeights | null {
  if (!model) return null;
  const norm = (league ?? "").toLowerCase().trim();
  return model.benter.liga_weights[norm] ?? null;
}

// ─── Public API: Golden Tests ───────────────────────────────────────

/**
 * Run all golden fixtures embedded in the model JSON against the loaded
 * runtime. Returns the count of failures (0 = perfect parity with Python).
 *
 * Tolerance defaults to 1e-4 — matches v2's golden-test convention. The
 * dev-03 ensemble's float64 arithmetic should match Python within ~1e-10
 * for individual tree traversals, but ensemble-average + variance compound
 * up to ~1e-6 in practice.
 */
export function validateDev03GoldenTests(tolerance = 1e-4): {
  passed: number;
  failed: number;
  failures: string[];
} {
  if (!model || !model.golden_tests?.length) {
    return { passed: 0, failed: 0, failures: [] };
  }

  const failures: string[] = [];
  let passed = 0;

  for (const g of model.golden_tests) {
    const pred = dev03Predict(g.features as Dev03FeatureInput);
    if (!pred) {
      failures.push(`${g.name}: null prediction`);
      continue;
    }
    const checks: Array<[string, number, number]> = [
      ["home_mean", pred.lambdaH_mean, g.expected_home_lambda_mean],
      ["home_var", pred.lambdaH_var, g.expected_home_lambda_var],
      ["away_mean", pred.lambdaA_mean, g.expected_away_lambda_mean],
      ["away_var", pred.lambdaA_var, g.expected_away_lambda_var],
    ];
    let allOk = true;
    for (const [tag, got, expected] of checks) {
      const diff = Math.abs(got - expected);
      if (diff > tolerance) {
        failures.push(
          `${g.name}.${tag}: got=${got.toFixed(6)}, expected=${expected.toFixed(6)}, diff=${diff.toExponential(2)}`
        );
        allOk = false;
      }
    }
    if (allOk) passed++;
  }

  return { passed, failed: model.golden_tests.length - passed, failures };
}

// ─── Test-only helpers (exposed for unit tests) ─────────────────────

/** Reset module state — for test isolation. */
export function _resetForTests(): void {
  model = null;
  leagueIndex = new Map();
}
