// ═══════════════════════════════════════════════════════════════════════
// dev-03 Feature Builder — TS port of v4/m2_lambda + EloCalculator-lookup
//                          + TeamMomentumCalculator-lookup
//
// Sister module of `dev03-runtime.ts` (which runs LightGBM forward-passes).
// This module turns (home_team, away_team, league, per-team xG-history) into
// the 17-feature `Dev03FeatureInput` that the runtime expects.
//
// Split-of-responsibilities:
//   1. **Cache-backed lookups** (Elo, Momentum-snapshot, Momentum-norms,
//      League-constants) come from `public/dev03-feature-cache.json`
//      generated by `tools/v4/export_feature_cache.py`. Updated weekly via
//      cron — stale-tolerant (Elo + Momentum drift slowly).
//   2. **Per-match EWMA + ratios** computed locally from the per-team
//      xG-history that MatchdayContext already loads.
//
// This split is the bridge over the "browser can't load 87k history rows"
// problem: the GLOBAL aggregates need pre-computation, but the per-team
// last-16 EWMA needs only what the page already has.
//
// Function names + EWMA math are 1:1 ports from:
//   - `tools/v4/modules/m2_lambda/ewma.py`
//   - `tools/v4/modules/m2_lambda/estimator.py`
//   - `tools/v4/modules/m2_lambda/league_constants.py`
//   - `tools/v4/modules/m3_xg/elo.py` (only get_rating + get_elo_diff)
//   - `tools/v4/modules/m3_xg/team_momentum.py` (only get_features)
//
// Critical correctness contract: `buildDev03Features()` MUST produce a
// feature vector that, when passed to `dev03Predict()`, matches the Python
// reference within ~1e-6 (the level of float64 arithmetic + JSON round-trip).
//
// Calling convention: pass per-team xG-history NEWEST-FIRST (matches how
// MatchdayContext.loadCached + Supabase `team_xg_history` order it after
// `.order('match_date', { ascending: false })`).
// ═══════════════════════════════════════════════════════════════════════

import type { XGHistoryEntry } from "@/types/match";
import type { Dev03FeatureInput } from "./dev03-runtime";

// ─── Constants (1:1 with Python) ─────────────────────────────────────

const EWMA_HALFLIFE = 8.0;
const LOOKBACK_MATCHES = 16;
const MIN_TEAM_MATCHES = 4;

// Defaults from m2_lambda/league_constants.py
const DEFAULT_HOME_XG_AVG = 1.55;
const DEFAULT_AWAY_XG_AVG = 1.30;
const DEFAULT_HOME_ADVANTAGE = 0.25;
const DEFAULT_TOTAL_AVG = DEFAULT_HOME_XG_AVG + DEFAULT_AWAY_XG_AVG;

// From team_momentum.py
const Z_CLIP_MIN = -3.0;
const Z_CLIP_MAX = 3.0;

// ─── Types ───────────────────────────────────────────────────────────

export interface LeagueConstants {
  home_xg_avg: number;
  away_xg_avg: number;
  home_advantage: number;
  total_avg: number;
  n_matches: number;
  source: string;
}

export interface MomentumSnapshot {
  raw_lineup: number;
  raw_form: number;
  n_seen: number;
}

export interface MomentumNorms {
  mu_lineup: number;
  sd_lineup: number;
  mu_form: number;
  sd_form: number;
  computed_at?: string;
}

export interface Dev03FeatureCache {
  version: string;
  exported_at: string;
  data_window: {
    history_through: string;
    snapshot_date: string;
    n_history_rows: number;
  };
  league_constants: Record<string, LeagueConstants>;
  elo: Record<string, number>;
  elo_default: number;
  momentum: Record<string, MomentumSnapshot>;
  momentum_norms: Record<string, MomentumNorms>;
  momentum_default: MomentumSnapshot;
  meta?: Record<string, unknown>;
}

export interface TeamStrength {
  attack_xg: number;
  defense_xga: number;
  n_matches: number;
  ess: number;
  is_fallback: boolean;
}

export interface BuildFeaturesInput {
  homeTeam: string;
  awayTeam: string;
  league: string;
  /** Home team's xG-history, NEWEST-FIRST. Pass last ~16 matches. */
  hHistory: XGHistoryEntry[];
  /** Away team's xG-history, NEWEST-FIRST. Pass last ~16 matches. */
  aHistory: XGHistoryEntry[];
}

// ─── Module State ────────────────────────────────────────────────────

let cache: Dev03FeatureCache | null = null;

// ─── EWMA Primitives (port from m2_lambda/ewma.py) ───────────────────

/**
 * Effective sample size of an EWMA with `n` observations at given halflife.
 * Formula: ESS = (Σ w_k)² / Σ w_k²  where w_k = 0.5^(k/halflife).
 */
export function effectiveSampleSize(n: number, halflife: number): number {
  if (n <= 0 || halflife <= 0) return 0.0;
  let wSum = 0;
  let wSqSum = 0;
  for (let k = 0; k < n; k++) {
    const w = Math.pow(0.5, k / halflife);
    wSum += w;
    wSqSum += w * w;
  }
  return wSqSum > 0 ? (wSum * wSum) / wSqSum : 0.0;
}

/**
 * Exponentially-weighted mean over `values`. `values[0]` is the MOST RECENT
 * observation; weight = 0.5^(k/halflife).
 *
 * Returns NaN if finite-count < min_periods. NaN values are skipped (but
 * their index slot still counts toward weight decay — matches Python).
 */
export function ewmaRecentFirst(
  values: readonly number[],
  halflife: number,
  minPeriods = 1,
): number {
  if (halflife <= 0) {
    throw new Error(`halflife must be positive, got ${halflife}`);
  }
  if (values.length === 0) return NaN;

  let finiteCount = 0;
  for (const v of values) {
    if (Number.isFinite(v)) finiteCount++;
  }
  if (finiteCount < minPeriods) return NaN;

  let wSum = 0;
  let weightedSum = 0;
  for (let k = 0; k < values.length; k++) {
    const v = values[k];
    if (!Number.isFinite(v)) continue;
    const w = Math.pow(0.5, k / halflife);
    weightedSum += v * w;
    wSum += w;
  }
  if (wSum <= 0) return NaN;
  return weightedSum / wSum;
}

/** EWMA with deterministic fallback when finite-count < min_periods. */
export function ewmaWithFallback(
  values: readonly number[],
  halflife: number,
  fallback: number,
  minPeriods = 4,
): number {
  const v = ewmaRecentFirst(values, halflife, minPeriods);
  return Number.isNaN(v) ? fallback : v;
}

// ─── Cache loading ──────────────────────────────────────────────────

/**
 * Load the feature-cache JSON. Returns true on success, false on validation
 * failure. Validates structure but not data quality.
 */
export function loadFeatureCache(json: Dev03FeatureCache): boolean {
  if (!json || typeof json !== "object") {
    console.error("[dev03-features] cache must be an object");
    return false;
  }
  if (!json.league_constants || !json.elo || !json.momentum || !json.momentum_norms) {
    console.error("[dev03-features] cache missing required top-level keys");
    return false;
  }
  if (typeof json.elo_default !== "number" || !json.momentum_default) {
    console.error("[dev03-features] cache missing defaults");
    return false;
  }
  cache = json;
  console.log(
    `[dev03-features] Loaded cache: ${Object.keys(json.league_constants).length} leagues, ` +
    `${Object.keys(json.elo).length} elo + ${Object.keys(json.momentum).length} momentum snapshots ` +
    `(through ${json.data_window?.history_through?.slice(0, 10) ?? "?"})`
  );
  return true;
}

/** Module-level guard — call before any other public API. */
export function isFeatureCacheLoaded(): boolean {
  return cache !== null;
}

// ─── Lookup helpers ─────────────────────────────────────────────────

/**
 * League constants. Returns defaults (Bundesliga-like) if no cache loaded
 * or league unknown. The returned object's `source` field tells you why.
 */
export function getLeagueConstants(league: string): LeagueConstants {
  if (!cache) {
    return {
      home_xg_avg: DEFAULT_HOME_XG_AVG,
      away_xg_avg: DEFAULT_AWAY_XG_AVG,
      home_advantage: DEFAULT_HOME_ADVANTAGE,
      total_avg: DEFAULT_TOTAL_AVG,
      n_matches: 0,
      source: "cache_not_loaded",
    };
  }
  const norm = league.toLowerCase().trim();
  const lc = cache.league_constants[norm];
  if (!lc) {
    return {
      home_xg_avg: DEFAULT_HOME_XG_AVG,
      away_xg_avg: DEFAULT_AWAY_XG_AVG,
      home_advantage: DEFAULT_HOME_ADVANTAGE,
      total_avg: DEFAULT_TOTAL_AVG,
      n_matches: 0,
      source: "unknown_league_fallback",
    };
  }
  return lc;
}

/**
 * Elo rating for (team, league) at last cache update. If team unknown
 * (newly-promoted etc.), returns elo_default (= 1500.0 — EloCalculator's
 * neutral starting rating).
 */
export function getElo(team: string, league: string): number {
  if (!cache) return 1500.0;
  const key = `${league.toLowerCase().trim()}|${team}`;
  return cache.elo[key] ?? cache.elo_default;
}

/** Pure convenience: home_elo - away_elo. */
export function getEloDiff(homeTeam: string, awayTeam: string, league: string): number {
  return getElo(homeTeam, league) - getElo(awayTeam, league);
}

/**
 * Latest momentum snapshot for (team, league). For unknown team returns
 * the cache's `momentum_default` (typically all-zero, neutral signal).
 */
export function getMomentum(team: string, league: string): MomentumSnapshot {
  if (!cache) return { raw_lineup: 0.0, raw_form: 0.0, n_seen: 0 };
  const key = `${league.toLowerCase().trim()}|${team}`;
  return cache.momentum[key] ?? cache.momentum_default;
}

/**
 * Per-league normalization stats for momentum z-scoring. Returns sane
 * neutrals (mu=0, sd=1) when unknown — matches the Python `_get_norm`
 * fallback when no league data exists.
 */
export function getMomentumNorms(league: string): MomentumNorms {
  if (!cache) return { mu_lineup: 0.0, sd_lineup: 1.0, mu_form: 0.0, sd_form: 1.0 };
  const norm = league.toLowerCase().trim();
  const mn = cache.momentum_norms[norm];
  return mn ?? { mu_lineup: 0.0, sd_lineup: 1.0, mu_form: 0.0, sd_form: 1.0 };
}

// ─── Team strength (port from estimator.py::_team_strength) ──────────

/**
 * Compute attack/defense EWMA strength for a team given its history.
 *
 * `history` is the team's last-N matches NEWEST-FIRST. The function will
 * cap at `LOOKBACK_MATCHES` and require ≥ `MIN_TEAM_MATCHES` non-NaN xg
 * values to compute a real EWMA. Otherwise it falls back to `leagueAvgXg`.
 *
 * Mirror of Python's `_team_strength`. Used internally by buildDev03Features.
 */
export function computeTeamStrength(
  history: readonly XGHistoryEntry[],
  leagueAvgXg: number,
  halflife = EWMA_HALFLIFE,
  lookback = LOOKBACK_MATCHES,
  minMatches = MIN_TEAM_MATCHES,
): TeamStrength {
  // Cap to lookback window
  const slice = history.slice(0, lookback);
  // Filter to entries with finite xg (entries with NaN xg are dropped, NOT
  // index-gap'd — matches Python's `df = df[df['xg'].notna()]` behaviour)
  const usable = slice.filter(e => Number.isFinite(e.xg) && Number.isFinite(e.xga));
  const n = usable.length;

  if (n < minMatches) {
    return {
      attack_xg: leagueAvgXg,
      defense_xga: leagueAvgXg,
      n_matches: n,
      ess: n,
      is_fallback: true,
    };
  }

  const xg = usable.map(e => e.xg);
  const xga = usable.map(e => e.xga);
  const attack = ewmaWithFallback(xg, halflife, leagueAvgXg, minMatches);
  const defense = ewmaWithFallback(xga, halflife, leagueAvgXg, minMatches);
  const ess = effectiveSampleSize(n, halflife);
  return {
    attack_xg: attack,
    defense_xga: defense,
    n_matches: n,
    ess,
    is_fallback: false,
  };
}

// ─── Main assembly: build the 17-feature input for dev03Predict ──────

/**
 * Compose the full Dev03FeatureInput from per-team history + cache lookups.
 *
 * Steps (in Python's order):
 *   1. Lookup league constants → neutral_side_avg = total_avg / 2
 *   2. EWMA attack/defense for both teams (fall back to neutral if < 4 matches)
 *   3. Compute attack_ratio + defense_ratio (= 1.0 when team plays league-avg)
 *   4. Reconstruct lambda_h_naive + lambda_a_naive
 *   5. Compute attack_defense_ratio_h + _a interactions
 *   6. Lookup Elo + compute elo_diff
 *   7. Lookup momentum + apply per-league z-normalization + clip to [-3, 3]
 *      to produce lineup_quality_diff + form_streak_diff
 *
 * The returned object is directly consumable by `dev03Predict()` in
 * `dev03-runtime.ts`.
 */
export function buildDev03Features(input: BuildFeaturesInput): Dev03FeatureInput {
  const { homeTeam, awayTeam, league, hHistory, aHistory } = input;

  // Step 1: league constants
  const lc = getLeagueConstants(league);
  const totalAvg = lc.total_avg > 0 ? lc.total_avg : DEFAULT_TOTAL_AVG;
  const neutralSideAvg = totalAvg / 2.0;

  // Step 2: per-team strength
  const hStrength = computeTeamStrength(hHistory, neutralSideAvg);
  const aStrength = computeTeamStrength(aHistory, neutralSideAvg);

  // Step 3: attack/defense ratios (1.0 = league-average)
  const homeAttackRatio = hStrength.attack_xg / neutralSideAvg;
  const homeDefenseRatio = hStrength.defense_xga / neutralSideAvg;
  const awayAttackRatio = aStrength.attack_xg / neutralSideAvg;
  const awayDefenseRatio = aStrength.defense_xga / neutralSideAvg;

  // Step 4: lambda reconstruction (clamp afterwards to [0.3, 4.5] just like Python)
  const lambdaHRaw = lc.home_xg_avg * homeAttackRatio * awayDefenseRatio;
  const lambdaARaw = lc.away_xg_avg * awayAttackRatio * homeDefenseRatio;
  const lambdaHNaive = Math.max(0.3, Math.min(4.5, lambdaHRaw));
  const lambdaANaive = Math.max(0.3, Math.min(4.5, lambdaARaw));

  // Step 5: interaction terms
  const attackDefenseRatioH = homeAttackRatio * awayDefenseRatio;
  const attackDefenseRatioA = awayAttackRatio * homeDefenseRatio;

  // Step 6: elo
  const eloDiff = getEloDiff(homeTeam, awayTeam, league);

  // Step 7: momentum (z-normalized + clipped)
  const hMom = getMomentum(homeTeam, league);
  const aMom = getMomentum(awayTeam, league);
  const norms = getMomentumNorms(league);

  const safeSdLineup = norms.sd_lineup > 1e-6 ? norms.sd_lineup : 1.0;
  const safeSdForm = norms.sd_form > 1e-6 ? norms.sd_form : 1.0;

  const hLineupZ = (hMom.raw_lineup - norms.mu_lineup) / safeSdLineup;
  const aLineupZ = (aMom.raw_lineup - norms.mu_lineup) / safeSdLineup;
  const hFormZ = (hMom.raw_form - norms.mu_form) / safeSdForm;
  const aFormZ = (aMom.raw_form - norms.mu_form) / safeSdForm;

  const clipZ = (v: number): number =>
    Math.max(Z_CLIP_MIN, Math.min(Z_CLIP_MAX, hLineupZ - aLineupZ + 0)); // placeholder

  // Final diff features, clipped to [-3, 3] (matches Python team_momentum.py)
  const lineupQualityDiff = Math.max(
    Z_CLIP_MIN,
    Math.min(Z_CLIP_MAX, hLineupZ - aLineupZ),
  );
  const formStreakDiff = Math.max(
    Z_CLIP_MIN,
    Math.min(Z_CLIP_MAX, hFormZ - aFormZ),
  );
  void clipZ; // unused — kept for diagnostic clarity above

  return {
    home_attack_ratio: homeAttackRatio,
    home_defense_ratio: homeDefenseRatio,
    away_attack_ratio: awayAttackRatio,
    away_defense_ratio: awayDefenseRatio,
    home_ess: hStrength.ess,
    away_ess: aStrength.ess,
    league_home_avg: lc.home_xg_avg,
    league_away_avg: lc.away_xg_avg,
    league_home_advantage: lc.home_advantage,
    lambda_h_naive: lambdaHNaive,
    lambda_a_naive: lambdaANaive,
    attack_defense_ratio_h: attackDefenseRatioH,
    attack_defense_ratio_a: attackDefenseRatioA,
    elo_diff: eloDiff,
    lineup_quality_diff: lineupQualityDiff,
    form_streak_diff: formStreakDiff,
    league: league,
  };
}

// ─── Diagnostics ────────────────────────────────────────────────────

/**
 * Snapshot of all relevant lookups for one match — for debugging /
 * golden-test generation.
 */
export function debugFeatureBuild(input: BuildFeaturesInput): {
  features: Dev03FeatureInput;
  intermediates: {
    league_constants: LeagueConstants;
    home_strength: TeamStrength;
    away_strength: TeamStrength;
    home_elo: number;
    away_elo: number;
    home_momentum: MomentumSnapshot;
    away_momentum: MomentumSnapshot;
    momentum_norms: MomentumNorms;
    lambda_h_raw: number;
    lambda_a_raw: number;
  };
} {
  const lc = getLeagueConstants(input.league);
  const neutralSideAvg = (lc.total_avg > 0 ? lc.total_avg : DEFAULT_TOTAL_AVG) / 2.0;
  const hStrength = computeTeamStrength(input.hHistory, neutralSideAvg);
  const aStrength = computeTeamStrength(input.aHistory, neutralSideAvg);
  const hAr = hStrength.attack_xg / neutralSideAvg;
  const hDr = hStrength.defense_xga / neutralSideAvg;
  const aAr = aStrength.attack_xg / neutralSideAvg;
  const aDr = aStrength.defense_xga / neutralSideAvg;
  return {
    features: buildDev03Features(input),
    intermediates: {
      league_constants: lc,
      home_strength: hStrength,
      away_strength: aStrength,
      home_elo: getElo(input.homeTeam, input.league),
      away_elo: getElo(input.awayTeam, input.league),
      home_momentum: getMomentum(input.homeTeam, input.league),
      away_momentum: getMomentum(input.awayTeam, input.league),
      momentum_norms: getMomentumNorms(input.league),
      lambda_h_raw: lc.home_xg_avg * hAr * aDr,
      lambda_a_raw: lc.away_xg_avg * aAr * hDr,
    },
  };
}

// ─── Test-only helpers ─────────────────────────────────────────────

/** Reset module state — for test isolation. */
export function _resetFeatureCacheForTests(): void {
  cache = null;
}
