#!/usr/bin/env python3
"""
═══════════════════════════════════════════════════════════════════
FODZE — Current-Season Backtest (without re-training)
═══════════════════════════════════════════════════════════════════

The static cross-engine-oot-metrics.json (n=6691) covers the OLD
hold-out 2023-08 → 2024-06. But v2-oot-predictions.parquet ALSO
holds 8979 predictions for the CURRENT season (2025-08 → 2026-05),
generated by retrain_v2.py with strict no-leakage feature filtering.

These predictions were never scored because no merged-with-results
file existed. This script closes that gap:

  1. Load v2-oot-predictions.parquet for current-season window
  2. Pull actual results from team_xg_history (Supabase)
  3. Apply Dirichlet + Benter calibration variants
  4. Compute per-engine Brier + LogLoss + ECE
  5. Emit a current-season cross-engine-metrics.json

Output:
  tools/backtest/cross-engine-current-metrics.json

Usage:
  tools/venv/bin/python3 tools/backtest/score_current_season.py
  tools/venv/bin/python3 tools/backtest/score_current_season.py --from 2025-08-01
  tools/venv/bin/python3 tools/backtest/score_current_season.py --to 2026-04-26

The Brier numbers from this script are the ANSWER to the user's
2026-04-26 question: "warum müssen wir auf live-data warten? wir
haben doch historical predictions ohne lookforward bias."
═══════════════════════════════════════════════════════════════════
"""

import argparse
import json
import os
import sys
import urllib.request
import urllib.parse
from datetime import datetime
from typing import Optional

import numpy as np
import pandas as pd

PROJECT_ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
PRED_PARQUET = os.path.join(PROJECT_ROOT, "tools/backtest/v2-oot-predictions.parquet")
DIRICHLET_JSON = os.path.join(PROJECT_ROOT, "public/dirichlet-calibration.json")
BENTER_JSON = os.path.join(PROJECT_ROOT, "public/benter-weights.json")
OUTPUT_JSON = os.path.join(PROJECT_ROOT, "tools/backtest/cross-engine-current-metrics.json")

# ─── Env loader ────────────────────────────────────────────────
ENV_PATH = os.path.join(PROJECT_ROOT, ".env.local")
if os.path.exists(ENV_PATH):
    with open(ENV_PATH) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                k, v = line.split("=", 1)
                os.environ.setdefault(k, v)

SUPA_URL = os.environ.get("NEXT_PUBLIC_SUPABASE_URL") or os.environ.get("SUPABASE_URL")
SUPA_KEY = os.environ.get("SUPABASE_SERVICE_KEY")


# ─── Calibration loaders ────────────────────────────────────────

def load_dirichlet():
    with open(DIRICHLET_JSON) as f:
        d = json.load(f)
    return d["cluster_map"], d["clusters"], d["global"]


def load_benter():
    with open(BENTER_JSON) as f:
        d = json.load(f)
    # We use the v2 engine's per-league weights
    return d.get("engines", {}).get("v2", {})


# ─── Calibration math ───────────────────────────────────────────

def apply_dirichlet(probs, cluster_map, clusters, global_params, league):
    """probs = (h, d, a). Returns calibrated (h, d, a)."""
    cluster_key = cluster_map.get(league, "global")
    params = clusters.get(cluster_key, global_params)
    W, b = np.array(params["W"]), np.array(params["b"])
    logits = np.log(np.maximum(probs, 1e-9))
    z = W @ logits + b
    z -= np.max(z)
    e = np.exp(z)
    return e / e.sum()


def vig_remove(odds_h, odds_d, odds_a):
    """Proportional vig removal."""
    if any(o is None or pd.isna(o) or o <= 1 for o in [odds_h, odds_d, odds_a]):
        return None
    p = np.array([1.0 / odds_h, 1.0 / odds_d, 1.0 / odds_a])
    return p / p.sum()


def apply_benter(model_probs, pinn_probs, betas):
    """beta1 * log(model) + beta2 * log(pinn) → softmax."""
    if pinn_probs is None or betas is None:
        return model_probs
    b1, b2 = betas.get("beta1", 1.0), betas.get("beta2", 0.0)
    log_m = np.log(np.maximum(model_probs, 1e-9))
    log_p = np.log(np.maximum(pinn_probs, 1e-9))
    z = b1 * log_m + b2 * log_p
    z -= np.max(z)
    e = np.exp(z)
    return e / e.sum()


# ─── Supabase fetch ────────────────────────────────────────────

def normalize_team(name):
    if pd.isna(name):
        return ""
    return str(name).lower().replace(" ", "").replace("ü", "u").replace("ö", "o").replace("ä", "a").replace("ß", "ss").replace(".", "").replace("'", "")


def fuzzy_match(a, b):
    na, nb = normalize_team(a), normalize_team(b)
    if not na or not nb:
        return False
    if na == nb:
        return True
    if len(na) >= 4 and nb.startswith(na[:4]):
        return True
    if len(nb) >= 4 and na.startswith(nb[:4]):
        return True
    if len(na) >= 4 and na in nb:
        return True
    if len(nb) >= 4 and nb in na:
        return True
    return False


def fetch_results(date_from, date_to):
    """Fetch settled results from team_xg_history (home perspective)."""
    if not SUPA_URL or not SUPA_KEY:
        print("ERROR: Supabase env missing", file=sys.stderr)
        sys.exit(1)
    headers = {"apikey": SUPA_KEY, "Authorization": f"Bearer {SUPA_KEY}"}
    out = []
    offset = 0
    PAGE = 1000
    while True:
        params = urllib.parse.urlencode({
            "select": "team,opponent,league,match_date,goals_for,goals_against",
            "venue": "eq.home",
            "match_date": f"gte.{date_from}",
        })
        url = f"{SUPA_URL}/rest/v1/team_xg_history?{params}&match_date=lte.{date_to}&goals_for=not.is.null&limit={PAGE}&offset={offset}"
        req = urllib.request.Request(url, headers=headers)
        try:
            with urllib.request.urlopen(req) as r:
                page = json.loads(r.read().decode())
        except Exception as e:
            print(f"ERROR fetching: {e}", file=sys.stderr)
            sys.exit(1)
        if not page:
            break
        out.extend(page)
        offset += PAGE
        if len(page) < PAGE:
            break
    return out


def fetch_closing_odds(date_from, date_to):
    """Fetch closing odds from odds_closing_history."""
    headers = {"apikey": SUPA_KEY, "Authorization": f"Bearer {SUPA_KEY}"}
    out = []
    offset = 0
    PAGE = 1000
    while True:
        params = urllib.parse.urlencode({
            "select": "league,match_date,home_team,away_team,psch,pscd,psca",
            "match_date": f"gte.{date_from}",
        })
        url = f"{SUPA_URL}/rest/v1/odds_closing_history?{params}&match_date=lte.{date_to}&limit={PAGE}&offset={offset}"
        req = urllib.request.Request(url, headers=headers)
        try:
            with urllib.request.urlopen(req) as r:
                page = json.loads(r.read().decode())
        except Exception as e:
            print(f"ERROR fetching odds: {e}", file=sys.stderr)
            return []
        if not page:
            break
        out.extend(page)
        offset += PAGE
        if len(page) < PAGE:
            break
    return out


# ─── Scoring ────────────────────────────────────────────────────

def brier_1x2(p, outcome):
    """outcome ∈ {H, D, A}. p = (pH, pD, pA). Returns brier score."""
    yh = 1 if outcome == "H" else 0
    yd = 1 if outcome == "D" else 0
    ya = 1 if outcome == "A" else 0
    return (p[0] - yh) ** 2 + (p[1] - yd) ** 2 + (p[2] - ya) ** 2


def logloss_1x2(p, outcome):
    if outcome == "H":
        return -np.log(max(p[0], 1e-9))
    if outcome == "D":
        return -np.log(max(p[1], 1e-9))
    return -np.log(max(p[2], 1e-9))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--from", dest="date_from", default="2025-08-01",
                    help="Start of scoring window (default 2025-08-01)")
    ap.add_argument("--to", dest="date_to", default=datetime.utcnow().strftime("%Y-%m-%d"),
                    help="End of scoring window (default today)")
    args = ap.parse_args()

    print(f"\n═══ FODZE Current-Season Backtest ═══")
    print(f"   Window: {args.date_from} → {args.date_to}\n")

    # 1) Load predictions
    df_pred = pd.read_parquet(PRED_PARQUET)
    df_pred["match_date"] = pd.to_datetime(df_pred["match_date"]).dt.date.astype(str)
    df_pred = df_pred[(df_pred["match_date"] >= args.date_from) &
                      (df_pred["match_date"] <= args.date_to)]
    print(f"   Predictions: {len(df_pred)} (after date filter)")

    # 2) Load results
    results = fetch_results(args.date_from, args.date_to)
    print(f"   Results from team_xg_history: {len(results)}")

    # 3) Load closing odds
    odds = fetch_closing_odds(args.date_from, args.date_to)
    print(f"   Closing odds from odds_closing_history: {len(odds)}\n")

    # 4) Index for fuzzy join
    res_by_lg = {}
    for r in results:
        key = (r["league"], r["match_date"])
        res_by_lg.setdefault(key, []).append(r)

    odds_by_lg = {}
    for o in odds:
        key = (o["league"], o["match_date"])
        odds_by_lg.setdefault(key, []).append(o)

    # 5) Load calibration artifacts
    dir_cluster_map, dir_clusters, dir_global = load_dirichlet()
    benter_engine = load_benter()
    benter_leagues = benter_engine.get("leagues", {})
    benter_global = benter_engine.get("global", {"beta1": 1.0, "beta2": 0.0})

    # 6) Score every prediction with each variant
    metrics = {
        "v2_raw":       {"briers": [], "loglosses": [], "outcomes": [], "leagues": []},
        "v2_dirichlet": {"briers": [], "loglosses": [], "outcomes": [], "leagues": []},
        "v2_benter":    {"briers": [], "loglosses": [], "outcomes": [], "leagues": []},
    }
    matched = 0
    no_match = 0

    for _, p in df_pred.iterrows():
        # Find matching result via fuzzy team match
        candidates = res_by_lg.get((p["league"], p["match_date"]), [])
        match = None
        for c in candidates:
            if fuzzy_match(p["home_team"], c["team"]) and fuzzy_match(p["away_team"], c["opponent"]):
                match = c
                break
        if match is None:
            no_match += 1
            continue
        gh = int(match["goals_for"])
        ga = int(match["goals_against"])
        outcome = "H" if gh > ga else ("A" if gh < ga else "D")
        matched += 1

        raw_probs = np.array([p["prob_h_raw"], p["prob_d_raw"], p["prob_a_raw"]])

        # Dirichlet
        dir_probs = apply_dirichlet(raw_probs, dir_cluster_map, dir_clusters, dir_global, p["league"])

        # Benter (needs closing odds)
        odds_candidates = odds_by_lg.get((p["league"], p["match_date"]), [])
        odds_match = None
        for o in odds_candidates:
            if fuzzy_match(p["home_team"], o["home_team"]) and fuzzy_match(p["away_team"], o["away_team"]):
                odds_match = o
                break
        pinn_probs = None
        if odds_match:
            pinn_probs = vig_remove(odds_match.get("psch"), odds_match.get("pscd"), odds_match.get("psca"))
        bet_betas = benter_leagues.get(p["league"], benter_global)
        # Use Dirichlet output as model input to Benter (matches production behavior)
        ben_probs = apply_benter(dir_probs, pinn_probs, bet_betas)

        for variant, probs in [
            ("v2_raw", raw_probs),
            ("v2_dirichlet", dir_probs),
            ("v2_benter", ben_probs),
        ]:
            metrics[variant]["briers"].append(brier_1x2(probs, outcome))
            metrics[variant]["loglosses"].append(logloss_1x2(probs, outcome))
            metrics[variant]["outcomes"].append(outcome)
            metrics[variant]["leagues"].append(p["league"])

    print(f"   Matched: {matched} | Unmatched: {no_match}\n")
    if matched == 0:
        print("ERROR: zero matches resolved — check date range / team name normalization")
        sys.exit(1)

    # 7) Aggregate
    def agg(v):
        return {
            "n": len(v["briers"]),
            "brier": float(np.mean(v["briers"])),
            "log_loss": float(np.mean(v["loglosses"])),
            "outcome_counts": {o: int(sum(1 for x in v["outcomes"] if x == o)) for o in ["H", "D", "A"]},
        }

    summary = {
        "generated_at": datetime.utcnow().isoformat() + "Z",
        "window": {"from": args.date_from, "to": args.date_to},
        "n_matched": matched,
        "n_unmatched": no_match,
        "engines": {k: agg(v) for k, v in metrics.items()},
    }

    # 8) Compute uniform baseline + BSS
    H_rate = summary["engines"]["v2_raw"]["outcome_counts"]["H"] / matched
    D_rate = summary["engines"]["v2_raw"]["outcome_counts"]["D"] / matched
    A_rate = summary["engines"]["v2_raw"]["outcome_counts"]["A"] / matched
    base_brier = (
        H_rate * ((1 - H_rate) ** 2 + D_rate ** 2 + A_rate ** 2) +
        D_rate * (H_rate ** 2 + (1 - D_rate) ** 2 + A_rate ** 2) +
        A_rate * (H_rate ** 2 + D_rate ** 2 + (1 - A_rate) ** 2)
    )
    summary["base_rate_brier"] = float(base_brier)
    for k in summary["engines"]:
        summary["engines"][k]["bss"] = float(1 - summary["engines"][k]["brier"] / base_brier)

    # 9) Print overall + save
    print(f"━━━ Engine Comparison (n={matched}, current season) ━━━")
    print(f"  Base-rate Brier (climatology): {base_brier:.4f}\n")
    print(f"  {'Engine':18s} {'Brier':>8s} {'BSS':>8s} {'LogLoss':>9s}")
    print(f"  {'-'*46}")
    for engine, m in sorted(summary["engines"].items(), key=lambda x: x[1]["brier"]):
        print(f"  {engine:18s} {m['brier']:>8.4f} {m['bss']:>+8.4f} {m['log_loss']:>9.4f}")
    print()

    # 10) Per-league breakdown — does Dirichlet help in some leagues even
    # if it hurts overall? Decision-relevant for selective per-league activation.
    print(f"━━━ Per-League Brier (lower = better; * if Dirichlet beats raw) ━━━")
    print(f"  {'League':16s} {'n':>5s} {'raw':>8s} {'dir':>8s} {'ben':>8s} {'Δ dir-raw':>10s}")
    print(f"  {'-'*60}")
    league_results = {}
    for engine in ["v2_raw", "v2_dirichlet", "v2_benter"]:
        for lg, b in zip(metrics[engine]["leagues"], metrics[engine]["briers"]):
            league_results.setdefault(lg, {"v2_raw": [], "v2_dirichlet": [], "v2_benter": []})
            league_results[lg][engine].append(b)
    rows = []
    for lg, data in league_results.items():
        n = len(data["v2_raw"])
        if n < 50:  # too small per-league to be meaningful
            continue
        raw_b = float(np.mean(data["v2_raw"]))
        dir_b = float(np.mean(data["v2_dirichlet"]))
        ben_b = float(np.mean(data["v2_benter"]))
        rows.append((lg, n, raw_b, dir_b, ben_b))
    rows.sort(key=lambda r: r[3] - r[2])  # sort by Dirichlet improvement (best first)
    summary["per_league"] = []
    for lg, n, r, d, b in rows:
        delta = d - r
        marker = " *" if delta < 0 else "  "
        print(f"  {lg:16s} {n:>5d} {r:>8.4f} {d:>8.4f} {b:>8.4f} {delta:>+10.4f}{marker}")
        summary["per_league"].append({
            "league": lg, "n": n, "raw": r, "dirichlet": d, "benter": b,
        })
    print()
    helps = sum(1 for r in rows if r[3] - r[2] < 0)
    print(f"  Dirichlet beats raw in {helps}/{len(rows)} leagues (sorted by improvement above)")
    print()

    with open(OUTPUT_JSON, "w") as f:
        json.dump(summary, f, indent=2)
    print(f"✓ Saved: {OUTPUT_JSON}\n")


if __name__ == "__main__":
    main()
