// ═══════════════════════════════════════════════════════════════════════
// FODZE Transfermarkt Name Aliases
//
// Transfermarkt is a German platform and uses German versions of foreign
// team names ("Olympiakos Piräus", "Standard Lüttich", "OGC Nizza",
// "Sporting Lissabon", "RC Straßburg Alsace", "Real Saragossa").
// Odds-API, Understat, and football-data.co.uk use English or local
// variants ("Olympiakos", "Standard Liege", "Nice", "Sporting Lisbon",
// "Strasbourg", "Zaragoza").
//
// This map bridges the common gaps so resolveTransfermarktRef can go
// FODZE→TM without needing each naming permutation in TRANSFERMARKT_IDS
// (that's auto-generated and would drift each regeneration).
//
// Key = what FODZE / Odds-API uses  →  Value = what Transfermarkt uses.
// Additions are cheap; test by re-running the generate-matchday --injuries
// and watching the `·` skip count in the progress log.
// ═══════════════════════════════════════════════════════════════════════

export const TRANSFERMARKT_ALIASES = {
  // ─── Ligue 1 (German city names) ────────────────────────────────────
  "Nice":                      "OGC Nizza",
  "OGC Nice":                  "OGC Nizza",
  "Strasbourg":                "RC Straßburg Alsace",
  "RC Strasbourg":             "RC Straßburg Alsace",
  "Paris Saint Germain":       "FC Paris Saint-Germain",
  "Paris Saint-Germain":       "FC Paris Saint-Germain",
  "PSG":                       "FC Paris Saint-Germain",
  "Marseille":                 "Olympique Marseille",
  "Lyon":                      "Olympique Lyon",
  "Lille":                     "LOSC Lille",
  "Rennes":                    "FC Stade Rennes",
  "Stade Rennais":             "FC Stade Rennes",
  "Lens":                      "RC Lens",
  "Toulouse":                  "FC Toulouse",
  "Nantes":                    "FC Nantes",
  "Lorient":                   "FC Lorient",
  "Brest":                     "Stade Brest 29",
  "Auxerre":                   "AJ Auxerre",
  "Le Havre":                  "Le Havre AC",
  "Angers":                    "Angers SCO",
  "Metz":                      "FC Metz",

  // ─── Ligue 2 ────────────────────────────────────────────────────────
  "Stade de Reims":            "Stade Reims",
  "Reims":                     "Stade Reims",
  "Saint Etienne":             "AS Saint-Étienne",
  "Saint-Etienne":             "AS Saint-Étienne",
  "Saint-Étienne":             "AS Saint-Étienne",
  "St Etienne":                "AS Saint-Étienne",
  "Troyes":                    "ESTAC Troyes",
  "Amiens":                    "Amiens SC",
  "Montpellier":               "Montpellier HSC",
  "Guingamp":                  "EA Guingamp",
  "Clermont":                  "Clermont Foot 63",
  "Red Star":                  "Red Star FC",
  "Nancy":                     "AS Nancy-Lorraine",
  "Le Mans FC":                "FC Le Mans",
  "Stade Lavallois":           "Stade Laval",
  "Annecy":                    "FC Annecy",
  "Annecy FC":                 "FC Annecy",
  "Boulogne":                  "US Boulogne",
  "Grenoble":                  "Grenoble Foot 38",
  "Dunkerque":                 "USL Dunkerque",

  // ─── Süper Lig ──────────────────────────────────────────────────────
  "Goztepe":                   "Göztepe",
  "Genclerbirligi SK":         "Genclerbirligi Ankara",
  "Genclerbirligi":            "Genclerbirligi Ankara",
  "Gençlerbirliği":            "Genclerbirligi Ankara",
  "Fatih Karagumruk":          "Fatih Karagümrük",
  "Eyupspor":                  "Eyüpspor",
  "Kasimpasa SK":              "Kasimpasa",
  "Basaksehir":                "Basaksehir FK",
  "Istanbul Basaksehir":       "Basaksehir FK",
  "Besiktas":                  "Besiktas JK",
  "Gaziantep":                 "Gaziantep FK",
  "Rizespor":                  "Caykur Rizespor",

  // ─── Greek Super League ─────────────────────────────────────────────
  "Olympiakos":                "Olympiakos Piräus",
  "Olympiacos":                "Olympiakos Piräus",
  "Olympiakos Piraeus":        "Olympiakos Piräus",
  "PAOK":                      "PAOK Thessaloniki",
  "Panathinaikos":             "Panathinaikos Athen",
  "Panathinaikos Athens":      "Panathinaikos Athen",
  "AEK Athens":                "AEK Athen",
  "AEK":                       "AEK Athen",
  "Aris":                      "Aris Thessaloniki",
  "OFI Crete":                 "OFI Kreta",
  "OFI":                       "OFI Kreta",
  "AEL":                       "AE Larisa",
  "Larissa":                   "AE Larisa",
  "AEL Larissa":               "AE Larisa",
  "Atromitos":                 "Atromitos Athen",
  "Atromitos Athens":          "Atromitos Athen",
  "AE Kifisia FC":             "AE Kifisia",
  "Kifisia":                   "AE Kifisia",
  "Asteras Tripolis":          "Asteras Tripolis Aktor",
  "Volos":                     "Volos NFC",
  "Volos FC":                  "Volos NFC",
  "Panserraikos FC":           "Panserraikos",
  "Panetolikos Agrinio":       "Panetolikos",

  // ─── Jupiler Pro League (German + French + Dutch variants) ──────────
  "Standard Liege":            "Standard Lüttich",
  "Standard Liège":            "Standard Lüttich",
  "Royal Standard de Liege":   "Standard Lüttich",
  "Club Brugge":               "Club Brügge",
  "Club Brugge KV":            "Club Brügge",
  "Brugge":                    "Club Brügge",
  "Cercle Brugge":             "Cercle Brügge",
  "Sint Truiden":              "VV St. Truiden",
  "Sint-Truidense":            "VV St. Truiden",
  "STVV":                      "VV St. Truiden",
  "Anderlecht":                "RSC Anderlecht",
  "Genk":                      "KRC Genk",
  "Gent":                      "KAA Gent",
  "Charleroi":                 "Royal Charleroi SC",
  "Royal Charleroi":           "Royal Charleroi SC",
  "Westerlo":                  "KVC Westerlo",
  "Mechelen":                  "KV Mechelen",
  "KV Mechelen":               "KV Mechelen",
  "Dender":                    "FCV Dender EH",
  "Leuven":                    "Oud-Heverlee Leuven",
  "OH Leuven":                 "Oud-Heverlee Leuven",
  "Antwerp":                   "Royal Antwerpen FC",
  "Royal Antwerp":             "Royal Antwerpen FC",
  "Antwerp FC":                "Royal Antwerpen FC",
  "Union Saint-Gilloise":      "Union Saint-Gilloise",
  "Union SG":                  "Union Saint-Gilloise",
  "Zulte Waregem":             "Zulte Waregem",
  "SV Zulte Waregem":          "Zulte Waregem",
  "La Louviere":               "RAAL La Louvière",

  // ─── Primeira Liga ──────────────────────────────────────────────────
  "Sporting Lisbon":           "Sporting Lissabon",
  "Sporting":                  "Sporting Lissabon",
  "Sporting CP":               "Sporting Lissabon",
  "Benfica":                   "Benfica Lissabon",
  "Benfica Lisbon":            "Benfica Lissabon",
  "Braga":                     "SC Braga",
  "Vitória SC":                "Vitória Guimarães SC",
  "Vitoria Guimaraes":         "Vitória Guimarães SC",
  "Vitoria":                   "Vitória Guimarães SC",
  "Famalicão":                 "FC Famalicão",
  "Famalicao":                 "FC Famalicão",
  "Estoril":                   "GD Estoril Praia",
  "Gil Vicente":               "Gil Vicente FC",
  "Rio Ave":                   "Rio Ave FC",
  "Arouca":                    "FC Arouca",
  "Alverca":                   "FC Alverca",
  "Santa Clara":               "CD Santa Clara",
  "Moreirense":                "Moreirense FC",
  "Casa Pia":                  "Casa Pia AC",
  "Tondela":                   "CD Tondela",
  "Nacional":                  "CD Nacional",
  "CF Estrela":                "CF Estrela Amadora",
  "Estrela Amadora":           "CF Estrela Amadora",
  "AVS":                       "Avs Futebol",

  // ─── La Liga 2 (Spanish vs German city forms) ───────────────────────
  "Zaragoza":                  "Real Saragossa",
  "Real Zaragoza":             "Real Saragossa",
  "Deportivo":                 "Deportivo La Coruña",
  "Dep. La Coruna":            "Deportivo La Coruña",
  "Deportivo La Coruna":       "Deportivo La Coruña",
  "Almeria":                   "UD Almería",
  "Almería":                   "UD Almería",
  "Las Palmas":                "UD Las Palmas",
  "Valladolid":                "Real Valladolid",
  "Real Valladolid CF":        "Real Valladolid",
  "Malaga":                    "FC Málaga",
  "Málaga":                    "FC Málaga",
  "Gijon":                     "Sporting Gijón",
  "Cadiz CF":                  "FC Cádiz",
  "Cádiz CF":                  "FC Cádiz",
  "Cadiz":                     "FC Cádiz",
  "Granada":                   "FC Granada",
  "Leganes":                   "CD Leganés",
  "Leganés":                   "CD Leganés",
  "Andorra":                   "FC Andorra",
  "Andorra CF":                "FC Andorra",
  "Mirandes":                  "CD Mirandés",
  "Mirandés":                  "CD Mirandés",
  "Cordoba":                   "FC Córdoba",
  "Córdoba":                   "FC Córdoba",
  "Huesca":                    "SD Huesca",
  "Eibar":                     "SD Eibar",
  "Castellón":                 "CD Castellón",
  "Ceuta":                     "AD Ceuta FC",
  "Racing de Santander":       "Racing Santander",
  "Albacete":                  "Albacete Balompié",
  "Burgos":                    "Burgos CF",

  // ─── Championship ───────────────────────────────────────────────────
  "QPR":                       "Queens Park Rangers",
  "Southampton":               "FC Southampton",
  "Middlesbrough":             "FC Middlesbrough",
  "Millwall":                  "FC Millwall",
  "Watford":                   "FC Watford",
  "Portsmouth":                "FC Portsmouth",
  "Wrexham":                   "AFC Wrexham",

  // ─── Serie A (TM uses German city names) ────────────────────────────
  "Inter":                     "Inter Mailand",
  "Inter Milan":               "Inter Mailand",
  "Internazionale":            "Inter Mailand",
  "AC Milan":                  "AC Mailand",
  "Milan":                     "AC Mailand",
  "Napoli":                    "SSC Neapel",
  "SSC Napoli":                "SSC Neapel",
  "Roma":                      "AS Rom",
  "AS Roma":                   "AS Rom",
  "Lazio":                     "Lazio Rom",
  "SS Lazio":                  "Lazio Rom",
  "Juventus":                  "Juventus Turin",
  "Torino":                    "FC Turin",
  "Torino FC":                 "FC Turin",
  "Fiorentina":                "AC Florenz",
  "ACF Fiorentina":            "AC Florenz",
  "Bologna":                   "FC Bologna",
  "Genoa":                     "Genua CFC",
  "Atalanta":                  "Atalanta Bergamo",
  "Atalanta BC":               "Atalanta Bergamo",
  "Como":                      "Como 1907",
  "Sassuolo":                  "US Sassuolo",
  "Parma":                     "Parma Calcio 1913",
  "Udinese":                   "Udinese Calcio",
  "Cagliari":                  "Cagliari Calcio",
  "Pisa":                      "Pisa Sporting Club",
  "Lecce":                     "US Lecce",
  "Cremonese":                 "US Cremonese",

  // ─── Smaller leagues — likely useful aliases ────────────────────────
  "Man United":                "Manchester United",
  "Man Utd":                   "Manchester United",
  "Man City":                  "Manchester City",
  "Spurs":                     "Tottenham Hotspur",
  "Tottenham":                 "Tottenham Hotspur",
  "Wolves":                    "Wolverhampton Wanderers",
  "Leeds":                     "Leeds United",
  "Newcastle":                 "Newcastle United",
  "Brighton":                  "Brighton & Hove Albion",
  "West Ham":                  "West Ham United",
};
